spring:
  application:
    name: Eureka-Server

server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false           # 유레카 서버 자기 자신은 레지스트리에 등록하지 않음
    fetch-registry: false                 # 유레카 서버 자기 자신은 레지스트리에 등록하지 않음
  server:
    enable-self-preservation: false       # 정해진 시간 내에 생존 신호(Heartbeat)를 보내오지 않으면 유레카는 이를 인스턴스 문제가 아닌 네트워크 문제라고 간주하고
                                          # 생존 신호를 보내지 않는 인스턴스의 등록을 그대로 유지한다 이렇게 동작하는 모드가 '자기보호(Self-Preservation) 방식이다.
                                          # 실제로는 이 옵션을 true로 설정하는 것도 좋지만, 그렇게 하면 인스턴스가 등록 해제되는 것을 볼 수 없으므로 false로 설정한다.